name: 自动同步上游仓库

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: 检出你的仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 同步上游更新
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main           
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: Ps-Student-Catalog-Team/Ps-Student-Catalog  # 改成原仓库的路径
          upstream_sync_branch: main         
          # test_mode: true                  # 测试可开启

      - name: 有更新时输出提示
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "✅ 检测到上游有新提交，已同步"

      - name: 无更新时输出提示
        if: steps.sync.outputs.has_new_commits == 'false'
        run: echo "ℹ️ 上游无新提交，跳过同步"
